# Destroys terraform infrastructure in a dev environment any time that
#
# - a branch is deleted (that is not "main"), e.g. when a PR is merged
#
# - a pr is closed e.g. a PR is cancelled without merging
#
name: Terraform DEV CI/CD Cleanup
on:
  delete:
    branches:
      - "**"
      - "!main"
    paths:
      - "**.tf"
      - "**.tfvars"
  pull_request:
    types: 
      - closed
jobs:
  destroy:
    name: TF Dev Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: TF Setup
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '.'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET }}
          TF_CLI_ARGS: '-var-file="env/dev.tfvars" -backend-config="bucket=${{ secrets.AWS_DEV_TFSTATE_S3 }}"'
      - name: TF Destroy
        run: terraform destroy -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '.'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET }}
          TF_CLI_ARGS: '-var-file="env/dev.tfvars"'

