# Deploys a terraform infrastructure to !PRODUCTION! whenever a PR is merged
# Not
name: PROD Terraform CI/CD Pipeline
on:
  push:
    # only on pushes to main
    branches:
      - "main"
    # only if TF files changes
    paths:
      - "**.tf"
      - "**.tfvars"
jobs:
  tf-prod-cicd:
    # this is the part that makes the workflow run ONLY on a PR merge, not just a
    # push to main
    name: Infrastructure Jobs (prod)
    runs-on: ubuntu-latest
    steps:
    #   - name: Jim DEBUG
    #     run: |
    #       echo DEBUG
    #       echo "${{ github.event.pull_request.merged }} : " ${{ github.event.pull_request.merged }}
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: TF tagging (yor)
        uses: bridgecrewio/yor-action@main
#        env:
#          LOG_LEVEL: DEBUG
        with:
          parsers: Terraform
          config_file: .tag_config.yml

      - name: TF Setup (prod)
        uses: hashicorp/setup-terraform@v3

      - name: TF Init (prod)
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '.'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET }}
          TF_CLI_ARGS: '-var-file="env/prod.tfvars" -backend-config="bucket=${{ secrets.AWS_PROD_TFSTATE_S3 }}"'

      - name: TF Validate (prod)
        run: terraform validate

      - name: TF Plan (prod)
        run: terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '.'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET }}
          TF_CLI_ARGS: '-var-file="env/prod.tfvars"'

      - name: TF Apply (prod)
        run: terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '.'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET }}
          TF_CLI_ARGS: '-var-file="env/prod.tfvars"'
